;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Ability.Interaction",DevComment="")
+GameplayTagList=(Tag="FX.Impact",DevComment="")
+GameplayTagList=(Tag="FX.Impact.BrickWall",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Concrete",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Default",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Dirt",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Electric",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Flesh",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Glass",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Metal",DevComment="")
+GameplayTagList=(Tag="FX.Impact.Water",DevComment="")
+GameplayTagList=(Tag="FX.Test.Simple",DevComment="")
+GameplayTagList=(Tag="SpawnPoint.Dungeon.Second",DevComment="")
+GameplayTagList=(Tag="SpawnPoint.Dungeon.Start",DevComment="")
+GameplayTagList=(Tag="SpawnPoint.Dungeon.Third",DevComment="")
+GameplayTagList=(Tag="SpawnPoint.Faerin.Start",DevComment="")
+GameplayTagList=(Tag="SpawnPoint.Sector09.Start",DevComment="")
+GameplayTagList=(Tag="World.Dev.Playground",DevComment="")
+GameplayTagList=(Tag="World.Dungeon",DevComment="")
+GameplayTagList=(Tag="World.Fae",DevComment="")
+GameplayTagList=(Tag="World.Town",DevComment="")

